spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.119.185.39:3306/test_alex?characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: alex
    password: ALEXzcz123456

  data:
    redis:
      host: 47.119.185.39
      port: 6379
      password: ALEXzcz123456
      database: 0
